// Builds the icon set from the user-prepared emblem.
//
//  • public/logo.svg  — rounded "glass" tile, ADAPTIVE light/dark (embedded
//    @media swaps to a dark tile and lightens navy so the browser favicon reads
//    in dark mode). Source for the SVG favicon + the transparent pwa-*.png +
//    favicon.ico (all generated by `npm run generate-pwa-assets`, which bakes
//    the LIGHT inline variant — librsvg ignores <style>).
//  • maskable-icon-512x512.png + apple-touch-icon-180x180.png — rendered HERE,
//    from a CLEAN full-bleed square (opaque light, NO baked sheen/rim/rounding)
//    so iOS 26 can apply its own Liquid Glass (reflection/refraction/highlights)
//    on a neutral canvas. The pwa-assets config disables these two so it won't
//    clobber them.
//
// Run order: `node scripts/build-logo.mjs` THEN `npm run generate-pwa-assets`.
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import sharp from 'sharp'

const SRC = process.argv[2] || new URL('./logo-emblem.svg', import.meta.url)
const raw = readFileSync(SRC, 'utf8')

const m = raw.match(/<g id="Tavola-da-disegno11"[\s\S]*<\/g>/)
if (!m) throw new Error('emblem group not found')

// Tag each path with a colour class (keep the inline fill for light/raster).
const emblem = m[0]
  .replace(/(<path )(style="fill:rgb\(70,189,204\))/g, '$1class="c-teal" $2')
  .replace(/(<path )(style="fill:rgb\(29,56,101\))/g, '$1class="c-navy" $2')
  .replace(/(<path )(style="fill:rgb\(249,119,99\))/g, '$1class="c-coral" $2')

const CX = 1533, CY = 1533, SRC_W = 985, TARGET = 372
const S = (TARGET / SRC_W).toFixed(5)
const place = `translate(256 256) scale(${S}) translate(-${CX} -${CY})`

// ── 1. Rounded adaptive tile → public/logo.svg ──────────────────────────────
const logo = `<svg xmlns="http://www.w3.org/2000/svg" xmlns:serif="http://www.serif.com/" viewBox="0 0 512 512" width="512" height="512">
  <defs>
    <clipPath id="round"><rect width="512" height="512" rx="112"/></clipPath>
    <radialGradient id="tileLight" cx="50%" cy="36%" r="75%">
      <stop offset="0%" stop-color="#FFFFFF"/><stop offset="100%" stop-color="#E7ECF3"/>
    </radialGradient>
    <radialGradient id="tileDark" cx="50%" cy="34%" r="80%">
      <stop offset="0%" stop-color="#21344C"/><stop offset="60%" stop-color="#142133"/><stop offset="100%" stop-color="#0C1320"/>
    </radialGradient>
    <style>
      /*DARK-START*/@media (prefers-color-scheme:dark){.tilebg{fill:url(#tileDark)!important}.c-teal{fill:#5FD3E0!important}.c-navy{fill:#8AB2E4!important}.c-coral{fill:#FF8E70!important}.sheen{opacity:.10!important}.rim{stroke:#FFFFFF!important;stroke-opacity:.16!important}}/*DARK-END*/
    </style>
  </defs>
  <g clip-path="url(#round)">
    <rect class="tilebg" width="512" height="512" fill="url(#tileLight)"/>
    <ellipse class="sheen" cx="256" cy="36" rx="230" ry="176" fill="#FFFFFF" opacity="0.55"/>
  </g>
  <g transform="${place}">
    ${emblem}
  </g>
  <rect class="rim" x="1.5" y="1.5" width="509" height="509" rx="110.5" fill="none" stroke="#0E2436" stroke-opacity="0.08" stroke-width="2"/>
</svg>
`
writeFileSync(new URL('../public/logo.svg', import.meta.url), logo)

// ── 2. Clean full-bleed square → maskable + apple-touch (iOS applies glass) ──
const square = `<svg xmlns="http://www.w3.org/2000/svg" xmlns:serif="http://www.serif.com/" viewBox="0 0 512 512" width="512" height="512">
  <defs>
    <radialGradient id="t" cx="50%" cy="42%" r="80%">
      <stop offset="0%" stop-color="#FFFFFF"/><stop offset="100%" stop-color="#E7ECF3"/>
    </radialGradient>
  </defs>
  <rect width="512" height="512" fill="url(#t)"/>
  <g transform="${place}">
    ${emblem}
  </g>
</svg>
`
const pub = (f) => fileURLToPath(new URL(`../public/${f}`, import.meta.url))
const sq = Buffer.from(square)
await sharp(sq, { density: 512 }).resize(512, 512).png().toFile(pub('maskable-icon-512x512.png'))
await sharp(sq, { density: 512 }).resize(180, 180).png().toFile(pub('apple-touch-icon-180x180.png'))

console.log(`built logo.svg (scale ${S}) + clean maskable/apple-touch`)
