#!/usr/bin/env node
// Vendors the web fonts used by homelog.dev and docs.homelog.dev.
//
// Both sites used to pull Fraunces (and Space Mono on the landing) straight
// from fonts.googleapis.com, which hands every visitor's IP address to Google
// with no legal basis. This script downloads the same faces once and writes a
// self-hosted @font-face stylesheet, so no third party sees the visitor.
//
// Re-run it to pick up a new font version:
//   node scripts/vendor-fonts.mjs
//
// Only the latin and latin-ext subsets are kept — the sites are EN/IT only.

import { createHash } from 'node:crypto'
import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')

// Google serves woff2 (and per-weight static instances) only to browsers that
// advertise support; a bare fetch would get legacy ttf back.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'

const KEPT_SUBSETS = new Set(['latin', 'latin-ext'])

const TARGETS = [
  {
    name: 'landing',
    outDir: join(ROOT, 'landing', 'fonts'),
    query:
      'family=Fraunces:ital,opsz,wght@0,9..144,400;0,9..144,600;0,9..144,700;1,9..144,500&family=Space+Mono:wght@400;700&display=swap',
  },
  {
    name: 'docs-site',
    outDir: join(ROOT, 'docs-site', 'public', 'fonts'),
    query:
      'family=Fraunces:ital,opsz,wght@0,9..144,400;0,9..144,600;0,9..144,700;1,9..144,500&display=swap',
  },
]

// Splits the Google stylesheet into one record per @font-face, carrying the
// subset name from the `/* subset */` comment that precedes each block.
function parseFaces(css) {
  const faces = []
  const re = /\/\*\s*([a-z-]+)\s*\*\/\s*@font-face\s*\{([^}]*)\}/g
  let m
  while ((m = re.exec(css)) !== null) {
    const [, subset, body] = m
    const pick = (prop) => body.match(new RegExp(`${prop}:\\s*([^;]+);`))?.[1].trim()
    const url = body.match(/url\(([^)]+)\)/)?.[1]
    if (!url) continue
    faces.push({
      subset,
      family: pick('font-family').replace(/['"]/g, ''),
      style: pick('font-style'),
      weight: pick('font-weight'),
      unicodeRange: pick('unicode-range'),
      url,
    })
  }
  return faces
}

function slug(family) {
  return family.toLowerCase().replace(/\s+/g, '-')
}

async function main() {
  for (const target of TARGETS) {
    const cssUrl = `https://fonts.googleapis.com/css2?${target.query}`
    const res = await fetch(cssUrl, { headers: { 'User-Agent': UA } })
    if (!res.ok) throw new Error(`${target.name}: CSS fetch failed (${res.status})`)

    const faces = parseFaces(await res.text()).filter((f) => KEPT_SUBSETS.has(f.subset))
    if (faces.length === 0) throw new Error(`${target.name}: no latin faces found`)

    await mkdir(target.outDir, { recursive: true })

    // Download first, then name: when a family is requested with an axis range
    // Google returns ONE variable file for every weight, so several faces share
    // identical bytes. Writing them per weight would triple the payload.
    const downloads = []
    for (const face of faces) {
      const font = await fetch(face.url, { headers: { 'User-Agent': UA } })
      if (!font.ok) throw new Error(`${target.name}: ${face.url} failed (${font.status})`)
      const buf = Buffer.from(await font.arrayBuffer())
      downloads.push({ face, buf, hash: createHash('sha1').update(buf).digest('hex') })
    }

    const weightsPerHash = new Map()
    for (const d of downloads) {
      weightsPerHash.set(d.hash, (weightsPerHash.get(d.hash) ?? 0) + 1)
    }

    const nameByHash = new Map()
    const blocks = []
    let bytes = 0
    for (const { face, buf, hash } of downloads) {
      let name = nameByHash.get(hash)
      if (!name) {
        // A file backing more than one weight is the variable instance; drop
        // the weight from its name so it doesn't claim to be a static cut.
        const weight = weightsPerHash.get(hash) > 1 ? 'variable' : face.weight
        name = `${slug(face.family)}-${face.style}-${weight}-${face.subset}.woff2`
        nameByHash.set(hash, name)
        await writeFile(join(target.outDir, name), buf)
        bytes += buf.length
      }

      blocks.push(
        [
          '@font-face {',
          `  font-family: '${face.family}';`,
          `  font-style: ${face.style};`,
          `  font-weight: ${face.weight};`,
          '  font-display: swap;',
          `  src: url('./${name}') format('woff2');`,
          `  unicode-range: ${face.unicodeRange};`,
          '}',
        ].join('\n'),
      )
    }

    const header = [
      '/* Self-hosted web fonts — generated by scripts/vendor-fonts.mjs.',
      ' * Do not edit by hand; re-run the script instead.',
      ' *',
      ' * Served from our own origin on purpose: loading these from Google would',
      ' * disclose every visitor\'s IP address to a third party without consent.',
      ' */',
      '',
    ].join('\n')

    await writeFile(join(target.outDir, 'fonts.css'), `${header}${blocks.join('\n\n')}\n`)
    console.log(
      `✅ ${target.name}: ${faces.length} faces in ${nameByHash.size} files, ` +
        `${(bytes / 1024).toFixed(0)} KB → ${target.outDir}`,
    )
  }
}

main().catch((err) => {
  console.error(`❌ ${err.message}`)
  process.exit(1)
})
