export const currencies = [
  { code: 'EUR', symbol: '\u20ac', name: 'Euro' },
  { code: 'USD', symbol: '$', name: 'Dollaro USA' },
  { code: 'GBP', symbol: '\u00a3', name: 'Sterlina' },
  { code: 'CHF', symbol: 'Fr', name: 'Franco svizzero' },
  { code: 'JPY', symbol: '\u00a5', name: 'Yen giapponese' },
  { code: 'CAD', symbol: 'C$', name: 'Dollaro canadese' },
  { code: 'AUD', symbol: 'A$', name: 'Dollaro australiano' },
  { code: 'SEK', symbol: 'kr', name: 'Corona svedese' },
  { code: 'NOK', symbol: 'kr', name: 'Corona norvegese' },
  { code: 'DKK', symbol: 'kr', name: 'Corona danese' },
  { code: 'PLN', symbol: 'z\u0142', name: 'Zloty polacco' },
  { code: 'CZK', symbol: 'K\u010d', name: 'Corona ceca' },
  { code: 'HUF', symbol: 'Ft', name: 'Fiorino ungherese' },
  { code: 'TRY', symbol: '\u20ba', name: 'Lira turca' },
  { code: 'BRL', symbol: 'R$', name: 'Real brasiliano' },
  { code: 'CNY', symbol: '\u00a5', name: 'Yuan cinese' },
  { code: 'INR', symbol: '\u20b9', name: 'Rupia indiana' },
  { code: 'KRW', symbol: '\u20a9', name: 'Won sudcoreano' },
  { code: 'THB', symbol: '\u0e3f', name: 'Baht thailandese' },
]
